apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt-snowflake-run
  namespace: data-pipeline
  labels:
    app: dbt
    target: snowflake
spec:
  schedule: "0 */4 * * *"  # Every 4 hours
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dbt
            target: snowflake
        spec:
          restartPolicy: OnFailure
          containers:
          - name: dbt-snowflake
            image: data-pipeline/dbt:latest
            command: ["dbt", "run", "--target", "snowflake"]
            envFrom:
            - configMapRef:
                name: data-pipeline-config
            - configMapRef:
                name: snowflake-config
            env:
            - name: SNOWFLAKE_USER
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: username
            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: password
            - name: SNOWFLAKE_ROLE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: role
            - name: SNOWFLAKE_WAREHOUSE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: warehouse
            - name: SNOWFLAKE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: database
            - name: SNOWFLAKE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: account
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt-snowflake-test
  namespace: data-pipeline
  labels:
    app: dbt
    target: snowflake
spec:
  schedule: "30 */4 * * *"  # Every 4 hours, 30 minutes after run
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dbt
            target: snowflake
        spec:
          restartPolicy: OnFailure
          containers:
          - name: dbt-snowflake-test
            image: data-pipeline/dbt:latest
            command: ["dbt", "test", "--target", "snowflake"]
            envFrom:
            - configMapRef:
                name: data-pipeline-config
            - configMapRef:
                name: snowflake-config
            env:
            - name: SNOWFLAKE_USER
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: username
            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: password
            - name: SNOWFLAKE_ROLE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: role
            - name: SNOWFLAKE_WAREHOUSE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: warehouse
            - name: SNOWFLAKE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: database
            - name: SNOWFLAKE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: account
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"