apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-run
  namespace: data-pipeline
  labels:
    app: dbt
    job-type: run
spec:
  template:
    metadata:
      labels:
        app: dbt
        job-type: run
    spec:
      restartPolicy: OnFailure
      containers:
      - name: dbt
        image: data-pipeline/dbt:latest
        command: ["dbt", "run"]
        envFrom:
        - configMapRef:
            name: data-pipeline-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt-scheduled-run
  namespace: data-pipeline
  labels:
    app: dbt
    job-type: scheduled
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dbt
            job-type: scheduled
        spec:
          restartPolicy: OnFailure
          containers:
          - name: dbt
            image: data-pipeline/dbt:latest
            command: ["dbt", "run"]
            envFrom:
            - configMapRef:
                name: data-pipeline-config
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt-test
  namespace: data-pipeline
  labels:
    app: dbt
    job-type: test
spec:
  schedule: "30 */6 * * *"  # Every 6 hours, 30 minutes after run
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dbt
            job-type: test
        spec:
          restartPolicy: OnFailure
          containers:
          - name: dbt
            image: data-pipeline/dbt:latest
            command: ["dbt", "test"]
            envFrom:
            - configMapRef:
                name: data-pipeline-config
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"