apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-sa
  namespace: data-ingestion
  labels:
    app: postgresql
    component: database
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-sa
  namespace: data-ingestion
  labels:
    app: kafka
    component: streaming
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debezium-sa
  namespace: data-ingestion
  labels:
    app: debezium-connect
    component: cdc
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema-registry-sa
  namespace: data-ingestion
  labels:
    app: schema-registry
    component: schema-management
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-connect-sa
  namespace: data-ingestion
  labels:
    app: kafka-connect
    component: service-account
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-connect-role
  namespace: data-ingestion
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-connect-rolebinding
  namespace: data-ingestion
subjects:
- kind: ServiceAccount
  name: kafka-connect-sa
  namespace: data-ingestion
roleRef:
  kind: Role
  name: kafka-connect-role
  apiGroup: rbac.authorization.k8s.io