apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-sa
  namespace: data-ingestion
  labels:
    app: postgresql
    component: database
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-sa
  namespace: data-ingestion
  labels:
    app: kafka
    component: streaming
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debezium-sa
  namespace: data-ingestion
  labels:
    app: debezium-connect
    component: cdc
automountServiceAccountToken: false