# task6-schema-registry.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-jaas
  namespace: data-ingestion
  labels:
    app: schema-registry
    component: schema-management
    release: task6
data:
  jaas.conf: |
    SchemaRegistry {
      org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
      file="/etc/schema-registry/user.properties";
    };

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: data-ingestion
  labels:
    app: schema-registry
    component: schema-management
    release: task6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
        component: schema-management
        release: task6
    spec:
      serviceAccountName: schema-registry-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      enableServiceLinks: false  # needed to prevent "PORT is deprecated. Please use SCHEMA_REGISTRY_LISTENERS instead."
      containers:
      - name: schema-registry
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image: confluentinc/cp-schema-registry:7.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
          value: "_schemas"
        - name: SCHEMA_REGISTRY_SUPER_USERS
          value: "User:admin"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "kafka-headless.data-ingestion.svc.cluster.local:9092"
        - name: SCHEMA_REGISTRY_COMPATIBILITY_LEVEL
          value: "BACKWARD"
        - name: SCHEMA_REGISTRY_AUTHENTICATION_METHOD
          value: "BASIC"
        - name: SCHEMA_REGISTRY_AUTHENTICATION_REALM
          value: "SchemaRegistry"
        - name: SCHEMA_REGISTRY_AUTHENTICATION_ROLES
          value: "admin"
        - name: SCHEMA_REGISTRY_OPTS
          value: "-Djava.security.auth.login.config=/etc/schema-registry/jaas.conf"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: jaas-config
          mountPath: /etc/schema-registry/jaas.conf
          subPath: jaas.conf
        - name: auth-secret
          mountPath: /etc/schema-registry/user.properties
          subPath: user-info
      volumes:
      - name: jaas-config
        configMap:
          name: schema-registry-jaas
      - name: auth-secret
        secret:
          secretName: schema-registry-auth
---
kind: Service
apiVersion: v1
metadata:
  name: schema-registry
  namespace: data-ingestion
  labels:
    app: schema-registry
    component: schema-management
    release: task6
spec:
  selector:
    app: schema-registry
  ports:
  - protocol: TCP
    port: 8081
    targetPort: http
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: schema-registry-ext
  namespace: data-ingestion
  labels:
    app: schema-registry
    component: schema-management
    release: task6
spec:
  selector:
    app: schema-registry
  ports:
  - protocol: TCP
    port: 30081
    targetPort: http
    nodePort: 30082
  type: NodePort
