apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data-storage
type: Opaque
data:
  # postgres / postgres_password (base64 encoded)
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
  database: dHJhbnNhY3Rpb25zX2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: data-storage
type: Opaque
data:
  # analytics_user / analytics_password (base64 encoded)
  username: YW5hbHl0aWNzX3VzZXI=
  password: YW5hbHl0aWNzX3Bhc3N3b3Jk
  database: YW5hbHl0aWNz
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: data-pipeline
type: Opaque
data:
  # Fernet key and secret key for Airflow (base64 encoded)
  fernet-key: eW91ci1mZXJuZXQta2V5LWhlcmUtMzItY2hhcnMtbG9uZw==
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=
  # admin / admin (base64 encoded)
  admin-username: YWRtaW4=
  admin-password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: data-pipeline
type: Opaque
data:
  # AWS credentials (base64 encoded - replace with actual values)
  access-key-id: eW91ci1hd3MtYWNjZXNzLWtleS1pZA==
  secret-access-key: eW91ci1hd3Mtc2VjcmV0LWFjY2Vzcy1rZXk=
  region: dXMtd2VzdC0y