apiVersion: v1
kind: Secret
metadata:
  name: snowflake-secret
  namespace: data-pipeline
type: Opaque
data:
  # Base64 encoded Snowflake credentials (replace with actual values)
  account: eW91ci1zbm93Zmxha2UtYWNjb3VudA==  # your-snowflake-account
  username: eW91ci11c2VybmFtZQ==  # your-username
  password: eW91ci1wYXNzd29yZA==  # your-password
  role: eW91ci1yb2xl  # your-role
  warehouse: eW91ci13YXJlaG91c2U=  # your-warehouse
  database: eW91ci1kYXRhYmFzZQ==  # your-database
  schema: cHVibGlj  # public
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-config
  namespace: data-pipeline
data:
  SNOWFLAKE_ACCOUNT: "your-account.snowflakecomputing.com"
  SNOWFLAKE_DATABASE: "DATA_PIPELINE"
  SNOWFLAKE_WAREHOUSE: "COMPUTE_WH"
  SNOWFLAKE_ROLE: "ACCOUNTADMIN"
  SNOWFLAKE_SCHEMA: "PUBLIC"