apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  namespace: data-pipeline
  labels:
    app: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
      - name: data-generator
        image: data-pipeline/data-generator:latest
        envFrom:
        - configMapRef:
            name: data-pipeline-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import generator; print('OK')"
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import generator; print('OK')"
          initialDelaySeconds: 5
          periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-tools
  namespace: data-pipeline
  labels:
    app: kafka-tools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-tools
  template:
    metadata:
      labels:
        app: kafka-tools
    spec:
      containers:
      - name: kafka-tools
        image: data-pipeline/kafka-tools:latest
        envFrom:
        - configMapRef:
            name: data-pipeline-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - /app/scripts/health_check.py
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - python
            - /app/scripts/health_check.py
          initialDelaySeconds: 10
          periodSeconds: 30