version: 2

sources:
  - name: raw
    description: Raw data from our transaction system
    tables:
      - name: users
        description: User profile information
        columns:
          - name: user_id
            description: Unique identifier for users
            tests:
              - unique
              - not_null
          - name: email
            description: User email address
            tests:
              - unique
              - not_null
          - name: registration_date
            description: When the user registered
            tests:
              - not_null
          - name: tier
            description: User tier (bronze, silver, gold, platinum)
            tests:
              - accepted_values:
                  values: ['bronze', 'silver', 'gold', 'platinum']

      - name: products
        description: Product catalog information
        columns:
          - name: product_id
            description: Unique identifier for products
            tests:
              - unique
              - not_null
          - name: name
            description: Product name
            tests:
              - not_null
          - name: price
            description: Product price
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  strictly: true

      - name: transactions
        description: Transaction records
        columns:
          - name: transaction_id
            description: Unique identifier for transactions
            tests:
              - unique
              - not_null
          - name: user_id
            description: Reference to user
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'users')
                  field: user_id
          - name: product_id
            description: Reference to product
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'products')
                  field: product_id
          - name: total_amount
            description: Total transaction amount
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0

      - name: user_events
        description: User behavior events
        columns:
          - name: event_id
            description: Unique identifier for events
            tests:
              - unique
              - not_null
          - name: user_id
            description: Reference to user
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'users')
                  field: user_id
          - name: session_id
            description: Session identifier
            tests:
              - not_null
          - name: event_type
            description: Type of event
            tests:
              - not_null
              - accepted_values:
                  values: ['page_view', 'product_view', 'add_to_cart', 'remove_from_cart', 
                          'checkout_start', 'purchase', 'login', 'logout', 'search']